HACK: Adapter mit tsTimestamp als Lockingcolumn kompatibel machen
Da das ActiveRecord Locking (Optimistic) davon ausgeht, dass die "locking-column" ein Integer-Feld ist,
wird bei der Intialisierung ein 0 zugewiesen. Da wir aber einen SQL-Server Timestamp als Locking Feld verwenden,
und dieser ein Binary Datentyp ist, kann der Integer 0 nicht richtig serialisiert werden.

Der Hack dient als safety-guard und verhindert, dass die Method ConnectionAdapters::SQLServerColumn.binary_to_string
einen TypeError wirft. Folgender Fehler wird dadurch behoben:

TypeError: can't convert Fixnum into String
	from /Users/Hansli/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-sqlserver-adapter-3.0.6/lib/active_record/connection_adapters/sqlserver_adapter.rb:76:in `pack'
	from /Users/Hansli/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-sqlserver-adapter-3.0.6/lib/active_record/connection_adapters/sqlserver_adapter.rb:76:in `binary_to_string'
	from /Users/Hansli/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:82:in `type_cast'
	from /Users/Hansli/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/attribute_methods/read.rb:83:in `read_attribute'
	from /Users/Hansli/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/base.rb:1576:in `attribute_for_inspect'
	from /Users/Hansli/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/base.rb:1649:in `block in inspect'
	from /Users/Hansli/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/base.rb:1647:in `collect'
	from /Users/Hansli/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/base.rb:1647:in `inspect'
	from /Users/Hansli/.rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.1/lib/rails/commands/console.rb:44:in `start'
	from /Users/Hansli/.rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.1/lib/rails/commands/console.rb:8:in `start'
	from /Users/Hansli/.rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.1/lib/rails/commands.rb:23:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'